name: version_migration
description: Manages functions of code that need to run once on version updates in Flutter apps.
version: 2.0.10
homepage: https://github.com/yeniel/version_migration.git

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  package_info_plus: ^8.1.2
  shared_preferences: ^2.3.4
  platform: ^3.1.5
  file: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter